/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutColorSchemeRouteImport } from './routes/_layout/color-scheme'
import { Route as LayoutColorsPaletteRouteImport } from './routes/_layout/colors/palette'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutColorSchemeRoute = LayoutColorSchemeRouteImport.update({
  id: '/color-scheme',
  path: '/color-scheme',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutColorsPaletteRoute = LayoutColorsPaletteRouteImport.update({
  id: '/colors/palette',
  path: '/colors/palette',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/color-scheme': typeof LayoutColorSchemeRoute
  '/colors/palette': typeof LayoutColorsPaletteRoute
}
export interface FileRoutesByTo {
  '/color-scheme': typeof LayoutColorSchemeRoute
  '/': typeof LayoutIndexRoute
  '/colors/palette': typeof LayoutColorsPaletteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/color-scheme': typeof LayoutColorSchemeRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/colors/palette': typeof LayoutColorsPaletteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/color-scheme' | '/colors/palette'
  fileRoutesByTo: FileRoutesByTo
  to: '/color-scheme' | '/' | '/colors/palette'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/color-scheme'
    | '/_layout/'
    | '/_layout/colors/palette'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/color-scheme': {
      id: '/_layout/color-scheme'
      path: '/color-scheme'
      fullPath: '/color-scheme'
      preLoaderRoute: typeof LayoutColorSchemeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/colors/palette': {
      id: '/_layout/colors/palette'
      path: '/colors/palette'
      fullPath: '/colors/palette'
      preLoaderRoute: typeof LayoutColorsPaletteRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutColorSchemeRoute: typeof LayoutColorSchemeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutColorsPaletteRoute: typeof LayoutColorsPaletteRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutColorSchemeRoute: LayoutColorSchemeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutColorsPaletteRoute: LayoutColorsPaletteRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
